<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQUgGw5W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQUgGw5W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQUgGw5W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQUgGw5W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQUgGw5W\App_KernelDevDebugContainer([
    'container.build_hash' => 'QUgGw5W',
    'container.build_id' => 'f23e0560',
    'container.build_time' => 1618560642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQUgGw5W');
